# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Including surname', max_length=100, verbose_name='Full name')),
                ('short_name', models.CharField(help_text='Surname only or include initials when necessary: J.S. Bach', max_length=100, verbose_name='Short name')),
                ('nationality', models.CharField(max_length=30, verbose_name='Nationality')),
                ('birth', models.PositiveSmallIntegerField(verbose_name='Year of birth')),
                ('death', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of death')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Composer')),
            ],
        ),
    ]
