# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('landline_telephone', models.CharField(blank=True, max_length=255)),
                ('mobile_telephone', models.CharField(blank=True, max_length=255)),
                ('address_line_one', models.CharField(blank=True, max_length=255)),
                ('address_line_two', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('county_or_state', models.CharField(blank=True, max_length=255)),
                ('zip_or_postal_code', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(editable=False, null=True)),
                ('longitude', models.FloatField(editable=False, null=True)),
            ],
        ),
    ]
